name: Deploy Pokemon Cards

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Status
        run: |
          echo "Repository setup complete!"
          echo "To complete the card upload:"
          echo "1. Clone this repository locally"
          echo "2. Add all 207 card images"
          echo "3. Push to main branch"
          echo ""
          echo "Card images are ready in your local folder:"
          echo "C:\Users\ottaw\Documents\pokemon-cards-151"
